

const themes = {
  simple: {
    '--primary-color': '#0070f3',
    '--secondary-color': '#ff4081',
    '--background-color': '#ffffff',
    '--foreground-color': '#f0f0f0',
    '--header-color': '#171717',
    '--text-color': '#333333',
    '--button-background-color': 'var(--primary-color)',
    '--button-text-color': '#ffffff',
    '--button-hover-background-color': '#005bb5',
    '--border-color': '#eaeaea',
    '--box-shadow': '0 4px 6px rgba(0, 0, 0, 0.1)',
    '--font-sans': 'var(--font-geist-sans), -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif',
    '--font-mono': 'var(--font-geist-mono), Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace',
    '--status-text-color': '#000000',
    '--template-info-text-color': 'var(--text-color)',
    '--template-info-heading-color': 'var(--text-color)',
  },
  brutalist: {
    '--primary-color': '#ff0000',
    '--secondary-color': '#00ff00',
    '--background-color': '#ffffff',
    '--foreground-color': '#000000',
    '--header-color': '#000000',
    '--text-color': '#000000',
    '--button-background-color': '#000000',
    '--button-text-color': '#ffffff',
    '--button-hover-background-color': '#333333',
    '--border-color': '#000000',
    '--box-shadow': 'none',
    '--font-sans': 'monospace',
    '--font-mono': 'monospace',
    '--status-text-color': '#ffffff',
    '--template-info-text-color': '#ffffff',
    '--template-info-heading-color': '#ffffff',
  },
  '90s': {
    '--primary-color': '#00ffff',
    '--secondary-color': '#ff00ff',
    '--background-color': '#000000',
    '--foreground-color': '#333333',
    '--header-color': '#00ffff',
    '--text-color': '#00ff00',
    '--button-background-color': '#ff00ff',
    '--button-text-color': '#000000',
    '--button-hover-background-color': '#cc00cc',
    '--border-color': '#00ffff',
    '--box-shadow': '5px 5px 0px #ff00ff',
    '--font-sans': '"Press Start 2P", cursive',
    '--font-mono': '"Press Start 2P", cursive',
    '--status-text-color': '#ffffff',
    '--template-info-text-color': '#ffffff',
    '--template-info-heading-color': '#ffffff',
  },
  retro: {
    '--primary-color': '#a8dadc',
    '--secondary-color': '#457b9d',
    '--background-color': '#f1faee',
    '--foreground-color': '#e63946',
    '--header-color': '#1d3557',
    '--text-color': '#1d3557',
    '--button-background-color': '#e63946',
    '--button-text-color': '#f1faee',
    '--button-hover-background-color': '#c42c3a',
    '--border-color': '#a8dadc',
    '--box-shadow': '0 2px 4px rgba(0, 0, 0, 0.2)',
    '--font-sans': '"Roboto Slab", serif',
    '--font-mono': '"Roboto Mono", monospace',
    '--status-text-color': '#ffffff',
    '--template-info-text-color': '#ffffff',
    '--template-info-heading-color': '#ffffff',
  },
  minimalist: {
    '--primary-color': '#888888',
    '--secondary-color': '#cccccc',
    '--background-color': '#f8f8f8',
    '--foreground-color': '#e0e0e0',
    '--header-color': '#333333',
    '--text-color': '#555555',
    '--button-background-color': '#eeeeee',
    '--button-text-color': '#333333',
    '--button-hover-background-color': '#dddddd',
    '--border-color': '#dddddd',
    '--box-shadow': 'none',
    '--font-sans': '"Helvetica Neue", Arial, sans-serif',
    '--font-mono': '"SFMono-Regular", Consolas, "Liberation Mono", Menlo, monospace',
    '--status-text-color': '#333333',
    '--template-info-text-color': 'var(--text-color)',
    '--template-info-heading-color': 'var(--text-color)',
  },
  darkmode: {
    '--primary-color': '#4a90e2',
    '--secondary-color': '#7ed6df',
    '--background-color': '#282c34',
    '--foreground-color': '#3a3f4b',
    '--header-color': '#ffffff',
    '--text-color': '#e0e0e0',
    '--button-background-color': '#4a90e2',
    '--button-text-color': '#ffffff',
    '--button-hover-background-color': '#357bd8',
    '--border-color': '#444444',
    '--box-shadow': '0 2px 4px rgba(0, 0, 0, 0.3)',
    '--font-sans': '"Inter", sans-serif',
    '--font-mono': '"Fira Code", monospace',
    '--status-text-color': '#ffffff',
    '--template-info-text-color': 'var(--text-color)',
    '--template-info-heading-color': 'var(--text-color)',
  },
  vibrantpop: {
    '--primary-color': '#ff007f',
    '--secondary-color': '#00ffbf',
    '--background-color': '#f0f8ff',
    '--foreground-color': '#ffe600',
    '--header-color': '#8a2be2',
    '--text-color': '#333333',
    '--button-background-color': '#ff007f',
    '--button-text-color': '#ffffff',
    '--button-hover-background-color': '#cc0066',
    '--border-color': '#ff007f',
    '--box-shadow': '0 5px 15px rgba(255, 0, 127, 0.4)',
    '--font-sans': '"Comic Sans MS", cursive',
    '--font-mono': '"Lucida Console", monospace',
    '--status-text-color': '#000000',
    '--template-info-text-color': 'var(--text-color)',
    '--template-info-heading-color': 'var(--text-color)',
  },
  earthy: {
    '--primary-color': '#6b8e23',
    '--secondary-color': '#a0522d',
    '--background-color': '#f5f5dc',
    '--foreground-color': '#d2b48c',
    '--header-color': '#2f4f4f',
    '--text-color': '#556b2f',
    '--button-background-color': '#6b8e23',
    '--button-text-color': '#ffffff',
    '--button-hover-background-color': '#557a1e',
    '--border-color': '#8b4513',
    '--box-shadow': '0 2px 5px rgba(0, 0, 0, 0.15)',
    '--font-sans': '"Georgia", serif',
    '--font-mono': '"Courier New", monospace',
    '--status-text-color': 'var(--text-color)',
    '--template-info-text-color': 'var(--text-color)',
    '--template-info-heading-color': 'var(--text-color)',
  },
  cyberpunk: {
    '--primary-color': '#00ffff',
    '--secondary-color': '#ff00ff',
    '--background-color': '#1a1a1a',
    '--foreground-color': '#333333',
    '--header-color': '#00ffff',
    '--text-color': '#00ff00',
    '--button-background-color': '#ff00ff',
    '--button-text-color': '#000000',
    '--button-hover-background-color': '#cc00cc',
    '--border-color': '#00ffff',
    '--box-shadow': '0 0 10px #00ffff, 0 0 20px #ff00ff',
    '--font-sans': '"Electrolize", sans-serif',
    '--font-mono': '"Share Tech Mono", monospace',
    '--status-text-color': '#00ff00',
    '--template-info-text-color': 'var(--text-color)',
    '--template-info-heading-color': 'var(--text-color)',
  },
};

export default themes;
